server:
  port: 8000

  # this value is overwritten in values file
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://192.168.101.8:5432/card
    username: root
    password: devEnv
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.tool.hbm2ddl: INFO

springdoc:
  api-docs:
    enabled: true
    path: /docs
